### ISSUE TITLE
Mod not compliant with original license.

### ISSUE THREAD

**Issue by Dykam** [MrDimkasStudio/SolarFluxReborn#6]
I ran into this issue: BuildCraft/BuildCraft#3522 and figured out the cause was an outdated API class, as BuildCraft released their updated for 1.11. I wouldn't mind trying to update this myself, however this repository doesn't have the most recent source code, nor does it have [the licence documentation](https://github.com/Nauktis/SolarFlux/blob/0ba5d9e/LICENSE.md) attached which came with the Solar Flux source code (GPL).

**Comment by MrDimkasStudio** [comment]
I am going to say "No" to buildcraft API and just make my own. I'm annoyed with this type of storing API classes

**Comment by AEnterprise** [comment]
@MrDimkasStudio there is no need to ship api's yourself, you can use the optional annotation to prevent having to ship these classes

**Comment by Dykam** [comment]
@AEnterprise Wouldn't the solution be to just make it a classpath dependency with an `isModLoaded` wrapping the specific line? https://github.com/MrDimkasStudio/SolarFluxReborn/blob/4946c/src/main/java/com/mrdimka/solarfluxreborn/utility/Utils.java#L45

**Comment by AEnterprise** [comment]
yep, an is mod loaded check with a bouncer method in a seperate class (that doesn't get call or loaded when BC is not loaded to prevent crashing when the class is not found) would do the trick

then unless that method is removed from the api class it won't break or blow up when a newer version of the api is used
